### ISSUE TITLE
When Builder save fields.yaml with Repeater field, he add error text in it 

### ISSUE THREAD

**Issue by digorec** [rainlab/builder-plugin#106]
Before edit file:

```
tabs:
    fields:
        caption:
            label: Caption
            oc.commentPosition: ''
            span: auto
            type: text
            tab: Main
        html:
            label: Html
            size: giant
            language: php
            span: full
            type: codeeditor
            tab: HTML
        manuals:
            label: Mans
            oc.commentPosition: ''
            prompt: 'Add new item'
            span: full
            type: repeater
            tab: Manuals
            form:
                fields:
                    manual_caption:
                        label: Text
                        span: auto
                        type: text
                    manual_file:
                        label: 'File upload'
                        span: auto
                        type: text
```

After save:

```
fields:
    manual_caption:
        label: Text
        span: auto
        type: text
        tab: Manuals
    manual_file:
        label: 'File upload'
        span: auto
        type: text
        tab: Manuals
tabs:
    fields:
        caption:
            label: Caption
            oc.commentPosition: ''
            span: auto
            type: text
            tab: Main
        html:
            label: Html
            size: giant
            language: php
            span: full
            type: codeeditor
            tab: HTML
        manuals:
            label: Mans
            oc.commentPosition: ''
            prompt: 'Add new item'
            span: full
            type: repeater
            tab: Manuals
            form:
                fields:
                    manual_caption:
                        label: Text
                        span: auto
                        type: text
                    manual_file:
                        label: 'File upload'
                        span: auto
                        type: text
'': {  }

```

Builder v/ 1.0.11
October v/ 361
