### ISSUE TITLE
Add showSearch to dropdown properties grid

### ISSUE THREAD

**Issue by meysammahfouzi** [rainlab/builder-plugin#144]
It seems that it's not possible to set `showSearch` from the properties grid of a [dropdown](https://octobercms.com/docs/backend/forms#field-dropdown):

![dropdown](https://cloud.githubusercontent.com/assets/14848008/23625373/29da0138-02be-11e7-8dcc-c39a27b1b892.PNG)

Could you please add it? Otherwise we have to manually update the yaml file:

```
status:
    label: Blog Post Status
    type: dropdown
    showSearch: false
```
