### ISSUE TITLE
SubMenu Items not highlighted

### ISSUE THREAD

**Issue by datune** [rainlab/builder-plugin#173]
One main menu item, two sub menu items. 

The first sub menu item has the same URL as the main menu item, so clicking on the main menu item or the first sub menu item links to the same "view", as such, both should be highlighted, and they are. The second sub menu item, called Groups, should, when clicked, highlight the main menu item, and itself. However, only the main menu item is highlighted, and both sub menu items are inactive. 

Am I missing the obvious or what's going on here?

Content of plugin.yaml:
```
...
navigation:
    main-menu-item:
        label: Main
        url: name/space/plug
        icon: icon-question-circle
        sideMenu:
            side-menu-item:
                label: SubSameAsMain
                url: name/space/plug
                icon: icon-question-circle
            side-menu-item2:
                label: Groups
                url: name/space/plug2
                icon: icon-archive
...
```
