### ISSUE TITLE
Add unexpected quote on custom switch text

### ISSUE THREAD

**Issue by webbati** [rainlab/builder-plugin#308]
Customizing the switch text with the on and off parameters in the file fields.yaml when you modify the form via the builder adds quotation marks in an unexpected way

```

'on': Yes

'off': 'No'
```

**Comment by LukeTowers** [comment]
Not sure what the issue is, they both are valid YAML are they not?

**Comment by webbati** [comment]
Property names should not have quotes and only the second value has them

```
my_field:
            label: 'My label'
            span: left
            type: switch
            'on': Yes
            'off': 'No'
```

it should be so

```
my_field:
            label: 'My label'
            span: left
            type: switch
            on: Yes
            off: No
```

or at least

```
my_field:
            label: 'My label'
            span: left
            type: switch
            on: 'Yes'
            off: 'No'
```


I'm wrong?
