### ISSUE TITLE
Importing a Tailor Model with `multisite: sync` throws Exception

### ISSUE THREAD

**Issue by TimFoerster** [rainlab/builder-plugin#377]
```
"Call to undefined method Tailor\Classes\Blueprint\GlobalBlueprint::useMultisiteSync()" on line 512 of /var/www/html/vendor/october/rain/src/Extension/ExtendableTrait.php

#0 /var/www/html/vendor/october/rain/src/Extension/Extendable.php(55): October\Rain\Extension\Extendable->extendableCall('useMultisiteSyn...', Array)
#1 /var/www/html/plugins/rainlab/builder/classes/blueprintgenerator/ModelContainer.php(266): October\Rain\Extension\Extendable->__call('useMultisiteSyn...', Array)
#2 /var/www/html/plugins/rainlab/builder/classes/blueprintgenerator/HasModels.php(130): RainLab\Builder\Classes\BlueprintGenerator\ModelContainer->getMultisiteDefinition()
#3 /var/www/html/plugins/rainlab/builder/classes/blueprintgenerator/HasModels.php(103): RainLab\Builder\Classes\BlueprintGenerator->extendModelWithModelSpecs(Object(RainLab\Builder\Models\ModelModel))
#4 /var/www/html/plugins/rainlab/builder/classes/blueprintgenerator/HasModels.php(25): RainLab\Builder\Classes\BlueprintGenerator->makeModelModel()
#5 /var/www/html/plugins/rainlab/builder/classes/BlueprintGenerator.php(125): RainLab\Builder\Classes\BlueprintGenerator->validateModel()
[...]
```

with tailor model 

```
uuid: edcd102e-0525-4e4d-b07e-633ae6c18db6
handle: Blog\Post
type: stream
name: Post
drafts: true
multisite: sync

primaryNavigation:
    label: Blog
    icon: octo-icon-file
    iconSvg: modules/tailor/assets/images/blog-icon.svg
    order: 350

navigation:
    icon: octo-icon-pencil
    order: 100

groups:
    regular_post:
        name: Regular Post
        fields:
            content:
                tab: Edit
                label: Content
                type: richeditor
                span: adaptive

            _blog_post_content:
                type: mixin
                source: Blog\PostContent

    markdown_post:
        name: Markdown Post
        fields:
            content:
                tab: Edit
                label: Content
                type: markdown
                span: adaptive

            _blog_post_content:
                type: mixin
                source: Blog\PostContent

```

- Laravel Framework 9.52.16
- You are using October CMS version: v3.5.6
- "name": "rainlab/builder-plugin", "version": "v2.0.5"
