### ISSUE TITLE
Is it possible to modify list settings using the Builder?

### ISSUE THREAD

**Issue by jfoliveira** [rainlab/builder-plugin#72]
When a new list is added to a plugin a `config_list.yaml` file is created under the controller folder.
I couldn't find how to modify the values in this file using the builder.

Some of the properties I would like to be able to change using the inspector are:
```yaml
recordUrl: 'acme/plugin/controller/preview/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: '10'
showSorting: 1
showTree: true
treeExpanded: true
```
Is this currently possible? How?
