### ISSUE TITLE
Form Dropdown Option for Mysql Null

### ISSUE THREAD

**Issue by sammyschnei** [rainlab/builder-plugin#98]
Builder doesn't seem to allow the creation of a backend dropdown menu element that can set a database setting to null. When editing a dropdown element in the module form, the 'Key' part of an item can't be blank. But writing anything like `null` for the key places a string `'null'` in the Yaml file.

I would think this could be easily avoided by editing the Yaml file to remove the quotes around `'null'`, e.g.,

```
fields:
    alt_zone:
        label: 'Alternate Time Zone'
        options:
            null: (none)
            America/New_York: 'US Eastern Time'
```

However, this just produces an empty string in the database. Other variations of `Null`, `NULL`, or `~` also produce `''` in the database rather than true nulls.

The column is set as nullable in the table configuration.
